# Generated by Django 5.2.17 on 2026-09-22 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, help_text='email or messenger handle', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(help_text='external identifier', max_length=64, unique=True)),
                ('tier', models.CharField(choices=[('individual', 'individual'), ('company', 'company')], default='individual', max_length=16)),
                ('state', models.CharField(choices=[('available', 'available'), ('reserved', 'reserved'), ('issued', 'issued'), ('expired', 'expired'), ('revoked', 'revoked')], db_index=True, default='available', max_length=16)),
                ('cost_cents', models.PositiveIntegerField(default=0, help_text='acquisition cost in cents', validators=[django.core.validators.MinValueValidator(0)])),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ref'],
                'indexes': [models.Index(fields=['state', 'expires_at'], name='inventory_u_state_4f7595_idx')],
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_days', models.PositiveSmallIntegerField()),
                ('price_cents', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('previous_expires_at', models.DateTimeField(blank=True, null=True)),
                ('new_expires_at', models.DateTimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='inventory.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(db_index=True)),
                ('warranty_days', models.PositiveSmallIntegerField(default=7)),
                ('warranty_until', models.DateTimeField(db_index=True)),
                ('price_cents', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='inventory.client')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='inventory.unit')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.CharField(default='system', max_length=150)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='inventory.issue')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='inventory.unit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('state', models.CharField(choices=[('open', 'open'), ('approved', 'approved'), ('rejected', 'rejected')], default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='inventory.issue')),
                ('replacement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_for', to='inventory.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='renewal', max_length=32)),
                ('for_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='inventory.unit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('unit', 'kind', 'for_expires_at'), name='one_reminder_per_expiry')],
            },
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('unit',), name='one_active_issue_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='warrantyclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'open')), fields=('issue',), name='one_open_claim_per_issue'),
        ),
    ]
