# Generated by Django 5.2.17 on 2026-09-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='warrantyclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'open')), fields=('issue',), name='one_open_claim_per_issue'),
        ),
    ]
